#!/bin/bash

# Prevent multiple instances
if pgrep -f "$(basename "$0")" | grep -vq "$$"; then
    exit 0
fi

export DISPLAY=:0

while true; do
    # Get the current battery percentage
    battery_level=$(cat /sys/class/power_supply/BAT0/capacity)

    # Check if the battery is discharging and below 20%
    charging_status=$(cat /sys/class/power_supply/BAT0/status)
    if [ "$charging_status" == "Discharging" ] && [ "$battery_level" -le 20 ]; then
        notify-send --urgency=critical --expire-time=10000 "Low Battery!" "Battery level is ${battery_level}%"
    fi

    # Wait 5 minutes before checking again
    sleep 300
done
